let me=null, folders=[], currentFolder=null;
const $=s=>document.querySelector(s);
async function api(url,opts={}){const r=await fetch(url,opts);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||"Request failed");return d}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function bytes(n){if(n<1024)return n+" B";if(n<1048576)return (n/1024).toFixed(1)+" KB";if(n<1073741824)return (n/1048576).toFixed(1)+" MB";return (n/1073741824).toFixed(1)+" GB"}
function modal(html){$("#modalContent").innerHTML=html;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
$("#closeModal").onclick=closeModal;
async function boot(){
 try{me=(await api("/api/me")).user;showApp();await loadFolders();await loadDocs();}catch{showLogin()}
}
function showLogin(){$("#login").classList.remove("hidden");$("#app").classList.add("hidden")}
function showApp(){$("#login").classList.add("hidden");$("#app").classList.remove("hidden");$("#userBadge").textContent=`${me.name} · ${me.role}`;document.querySelectorAll(".admin-nav").forEach(x=>x.classList.toggle("hidden",me.role!=="admin"))}
$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent="";try{const d=await api("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("#email").value,password:$("#password").value})});me=d.user;showApp();await loadFolders();await loadDocs()}catch(e){$("#loginError").textContent=e.message}}
$("#logoutBtn").onclick=async()=>{await api("/api/logout",{method:"POST"});location.reload()}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));n.classList.add("active");document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$("#"+n.dataset.page+"Page").classList.remove("hidden");if(n.dataset.page==="dashboard")loadDashboard();if(n.dataset.page==="users")loadUsers();if(n.dataset.page==="audit")loadAudit()});
async function loadFolders(){
 folders=(await api("/api/folders")).folders;
 const sel=$("#folderSelect");sel.innerHTML=`<option value="">All accessible folders</option>`+folders.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join("");
 $("#folderGrid").innerHTML=folders.map(f=>`<div class="folder-card" data-id="${f.id}">📁 ${esc(f.name)}</div>`).join("");
 document.querySelectorAll(".folder-card").forEach(x=>x.onclick=()=>{currentFolder=Number(x.dataset.id);sel.value=currentFolder;loadDocs()});
}
$("#folderSelect").onchange=()=>{currentFolder=$("#folderSelect").value?Number($("#folderSelect").value):null;loadDocs()}
$("#search").oninput=()=>loadDocs();
$("#refreshBtn").onclick=()=>{loadFolders();loadDocs()}
async function loadDocs(){
 const q=encodeURIComponent($("#search").value||"");const fid=currentFolder?`&folder_id=${currentFolder}`:"";
 const docs=(await api(`/api/documents?q=${q}${fid}`)).documents;
 $("#docsBody").innerHTML=docs.length?docs.map(d=>`<tr><td>📄 ${esc(d.original_name)}</td><td>v${d.current_version}</td><td>${bytes(d.size)}</td><td>${new Date(d.updated_at).toLocaleString()}</td><td><div class="row-actions"><button onclick="downloadDoc(${d.id})">Download</button><button class="ghost" onclick="versions(${d.id},'${esc(d.original_name)}')">Versions</button><button class="ghost" onclick="newVersion(${d.id})">New version</button>${me.role==="admin"?`<button class="ghost" onclick="deleteDoc(${d.id})">Delete</button>`:""}</div></td></tr>`).join(""):`<tr><td colspan="5" class="muted">No documents found.</td></tr>`;
}
window.downloadDoc=id=>window.location=`/api/documents/${id}/download`;
window.versions=async(id,name)=>{const d=await api(`/api/documents/${id}/versions`);modal(`<h3>${name} — version history</h3>${d.versions.map(v=>`<div class="permission-row"><span>Version ${v.version}<br><small>${esc(v.uploader)} · ${new Date(v.created_at).toLocaleString()} · ${bytes(v.size)}</small></span><button onclick="window.location='/api/documents/${id}/download?version=${v.version}'">Download</button></div>`).join("")}`)}
window.newVersion=id=>{modal(`<h3>Upload new version</h3><form id="versionForm"><input type="file" id="versionFile" required><button>Upload version</button></form>`);$("#versionForm").onsubmit=async e=>{e.preventDefault();const fd=new FormData();fd.append("file",$("#versionFile").files[0]);try{await api(`/api/documents/${id}/version`,{method:"POST",body:fd});closeModal();loadDocs()}catch(err){alert(err.message)}}}
window.deleteDoc=async id=>{if(confirm("Delete this document and all versions?")){await api(`/api/documents/${id}`,{method:"DELETE"});loadDocs()}}
$("#fileInput").onchange=async()=>{const file=$("#fileInput").files[0];if(!file)return;if(!currentFolder){alert("Select a folder first.");$("#fileInput").value="";return}const fd=new FormData();fd.append("file",file);fd.append("folder_id",currentFolder);try{await api("/api/documents/upload",{method:"POST",body:fd});loadDocs()}catch(e){alert(e.message)}$("#fileInput").value=""}
$("#newFolderBtn").onclick=()=>{modal(`<h3>Create folder</h3><form id="folderForm"><label>Folder name<input id="folderName" maxlength="120" required></label><label>Parent folder<select id="parentFolder"><option value="">Root</option>${folders.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join("")}</select></label><button>Create</button></form>`);$("#folderForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/folders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("#folderName").value,parent_id:$("#parentFolder").value||null})});closeModal();loadFolders()}catch(err){alert(err.message)}}}
async function loadDashboard(){const d=await api("/api/dashboard");$("#stats").innerHTML=[["Active users",d.users],["Folders",d.folders],["Documents",d.documents],["Stored size",bytes(d.bytes)]].map(x=>`<div class="stat"><span class="muted">${x[0]}</span><b>${x[1]}</b></div>`).join("");$("#recentBody").innerHTML=d.logs.map(l=>`<tr><td>${esc(l.user_name)}</td><td>${esc(l.action)}</td><td>${esc(l.entity_type)} #${l.entity_id||""}</td><td>${new Date(l.created_at).toLocaleString()}</td></tr>`).join("")}
async function loadUsers(){const d=await api("/api/users");$("#usersBody").innerHTML=d.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${u.role}</td><td>${u.active?"Active":"Disabled"}</td><td><button class="ghost" onclick="editUser(${u.id},'${esc(u.name)}','${u.role}',${u.active})">Edit</button></td></tr>`).join("")}
$("#addUserBtn").onclick=()=>{modal(`<h3>Add user</h3><form id="userForm"><label>Name<input id="uName" required></label><label>Email<input id="uEmail" type="email" required></label><label>Password<input id="uPass" type="password" minlength="8" required></label><label>Role<select id="uRole"><option>employee</option><option>admin</option></select></label><button>Create user</button></form>`);$("#userForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("#uName").value,email:$("#uEmail").value,password:$("#uPass").value,role:$("#uRole").value})});closeModal();loadUsers()}catch(err){alert(err.message)}}}
window.editUser=(id,name,role,active)=>{modal(`<h3>Edit user</h3><form id="editUser"><label>Name<input id="eName" value="${name}" required></label><label>Role<select id="eRole"><option ${role==="employee"?"selected":""}>employee</option><option ${role==="admin"?"selected":""}>admin</option></select></label><label>New password<input id="ePass" type="password" minlength="8"></label><label>Status<select id="eActive"><option value="1" ${active?"selected":""}>Active</option><option value="0" ${!active?"selected":""}>Disabled</option></select></label><button>Save changes</button></form>`);$("#editUser").onsubmit=async e=>{e.preventDefault();const body={name:$("#eName").value,role:$("#eRole").value,active:Number($("#eActive").value)};if($("#ePass").value)body.password=$("#ePass").value;try{await api(`/api/users/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});closeModal();loadUsers()}catch(err){alert(err.message)}}}
async function loadAudit(){const d=await api("/api/audit");$("#auditBody").innerHTML=d.logs.map(l=>`<tr><td>${esc(l.user_name)}</td><td>${esc(l.action)}</td><td>${esc(l.entity_type)} #${l.entity_id||""}</td><td>${esc(l.details||"")}</td><td>${new Date(l.created_at).toLocaleString()}</td></tr>`).join("")}
boot();
